//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPortofolio.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyPortofolio.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A &lt;strong&gt;robust&lt;/strong&gt; .NET 8 API providing a JSON-based CRUD interface for movie data. It features &lt;strong&gt;JWT authentication&lt;/strong&gt;, strict &lt;strong&gt;uniqueness constraints&lt;/strong&gt;, and a centralized error-handling middleware, optimized for asynchronous AJAX operations.
        ///.
        /// </summary>
        public static string API_Description {
            get {
                return ResourceManager.GetString("API_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à API - Movies.
        /// </summary>
        public static string API_Title {
            get {
                return ResourceManager.GetString("API_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A clan management application that lets you create, edit, and manage clans, handle users and their roles, and assign leaders for each clan..
        /// </summary>
        public static string ClanManager_Description {
            get {
                return ResourceManager.GetString("ClanManager_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Route protection based on roles, with a simple interface for both users and administrators..
        /// </summary>
        public static string ClanManager_Features {
            get {
                return ResourceManager.GetString("ClanManager_Features", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Download CV.
        /// </summary>
        public static string DownloadCV {
            get {
                return ResourceManager.GetString("DownloadCV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;strong&gt;A CV page&lt;/strong&gt; – where you can view and download my curriculum vitae..
        /// </summary>
        public static string Index_CVPage {
            get {
                return ResourceManager.GetString("Index_CVPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à I build reliable and maintainable applications, with close attention to code quality and a clear architecture..
        /// </summary>
        public static string Index_Description_1 {
            get {
                return ResourceManager.GetString("Index_Description_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à I enjoy proposing simple, user-friendly solutions. When necessary, I’m not afraid to challenge requirements in order to better understand the real needs and deliver truly appropriate solutions..
        /// </summary>
        public static string Index_Description_2 {
            get {
                return ResourceManager.GetString("Index_Description_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This portfolio presents a selection of personal projects that reflect the way I work..
        /// </summary>
        public static string Index_Description_3 {
            get {
                return ResourceManager.GetString("Index_Description_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This site is my personal portfolio. Its purpose is simple: to showcase the projects I have completed and highlight my technical skills..
        /// </summary>
        public static string Index_Goal {
            get {
                return ResourceManager.GetString("Index_Goal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hello, I am.
        /// </summary>
        public static string Index_Hello {
            get {
                return ResourceManager.GetString("Index_Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à My goal is to keep things clean, minimalist, and functional..
        /// </summary>
        public static string Index_MyObjective {
            get {
                return ResourceManager.GetString("Index_MyObjective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fullstack .NET developer, backend-oriented, passionate about clean code and simple, functional design..
        /// </summary>
        public static string Index_Presentation {
            get {
                return ResourceManager.GetString("Index_Presentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à a Fullstack .NET Developer with a strong backend focus, passionate about clean code and simple, functional design..
        /// </summary>
        public static string Index_Presentation_V2 {
            get {
                return ResourceManager.GetString("Index_Presentation_V2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;strong&gt;A Projects page&lt;/strong&gt; – where I list my personal and professional projects, each with a summary, a link to the deployed site, and a link to its public GitHub repository..
        /// </summary>
        public static string Index_ProjectsPage {
            get {
                return ResourceManager.GetString("Index_ProjectsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à View my projects.
        /// </summary>
        public static string Index_SeeProjects {
            get {
                return ResourceManager.GetString("Index_SeeProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à There you will find :.
        /// </summary>
        public static string Index_ToFind {
            get {
                return ResourceManager.GetString("Index_ToFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à My projects.
        /// </summary>
        public static string My_Projects {
            get {
                return ResourceManager.GetString("My_Projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Explore my portfolio to discover &lt;strong&gt;optimized&lt;/strong&gt; .NET 8 and Full-Stack projects, showcasing clean architecture, secure RESTful APIs, and modern frontend integrations..
        /// </summary>
        public static string Portfolio_Description {
            get {
                return ResourceManager.GetString("Portfolio_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Projects.
        /// </summary>
        public static string Projects {
            get {
                return ResourceManager.GetString("Projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à View on GitHub.
        /// </summary>
        public static string Projects_Git {
            get {
                return ResourceManager.GetString("Projects_Git", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Visit the site.
        /// </summary>
        public static string Projects_Visit {
            get {
                return ResourceManager.GetString("Projects_Visit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Swagger.
        /// </summary>
        public static string Swagger {
            get {
                return ResourceManager.GetString("Swagger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à View my CV.
        /// </summary>
        public static string ViewMyCV {
            get {
                return ResourceManager.GetString("ViewMyCV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A simple web application for managing movies, with pages to view a list of films, create, edit, and delete entries, all powered via AJAX calls to a backend API returning JSON..
        /// </summary>
        public static string WEB_Description {
            get {
                return ResourceManager.GetString("WEB_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à WEB - Movies.
        /// </summary>
        public static string WEB_Title {
            get {
                return ResourceManager.GetString("WEB_Title", resourceCulture);
            }
        }
    }
}
